// Project-owned PostgreSQL cluster. Requires PostgreSQL binaries on PATH.
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const root = path.resolve(__dirname, '..');
const directory = path.join(root, 'backend/.local/postgres');
const action = process.argv[2] || 'setup';
const port = 55440;
function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.error)
    throw new Error(
      `${command} could not run. Install PostgreSQL and add its bin directory to PATH.`,
    );
  if (result.status !== 0)
    throw new Error(`${command} failed (${result.status})`);
}
try {
  if (!['setup', 'start', 'stop', 'status'].includes(action))
    throw new Error('Use setup, start, stop or status');
  if (action === 'status') {
    run('pg_ctl', ['-D', directory, 'status']);
    process.exit(0);
  }
  if (action === 'stop') {
    run('pg_ctl', ['-D', directory, 'stop', '-m', 'fast']);
    process.exit(0);
  }
  if (!fs.existsSync(path.join(directory, 'PG_VERSION'))) {
    fs.mkdirSync(path.dirname(directory), { recursive: true });
    run('initdb', [
      '-D',
      directory,
      '-A',
      'trust',
      '--no-locale',
      '--encoding=UTF8',
    ]);
  }
  const status = spawnSync('pg_ctl', ['-D', directory, 'status'], {
    stdio: 'ignore',
  });
  if (status.error) throw status.error;
  if (status.status !== 0)
    run('pg_ctl', [
      '-D',
      directory,
      '-l',
      path.join(path.dirname(directory), 'postgres.log'),
      '-o',
      `-p ${port} -h 127.0.0.1 -k ${os.tmpdir()}`,
      'start',
    ]);
  const user = os.userInfo().username;
  const databaseUrl = `postgresql://${encodeURIComponent(
    user,
  )}@127.0.0.1:${port}/grocerycompare_local`;
  const env = {
    ...process.env,
    DATABASE_URL: databaseUrl,
    NODE_ENV: 'development',
    ALLOW_DEMO_DATA: 'true',
  };
  if (action === 'setup') {
    const existing = spawnSync(
      'psql',
      [
        '-h',
        '127.0.0.1',
        '-p',
        String(port),
        '-U',
        user,
        '-d',
        'postgres',
        '-tAc',
        "SELECT 1 FROM pg_database WHERE datname='grocerycompare_local'",
      ],
      { encoding: 'utf8' },
    );
    if (existing.status !== 0)
      throw new Error('Could not inspect the project database');
    if (existing.stdout.trim() !== '1')
      run('createdb', [
        '-h',
        '127.0.0.1',
        '-p',
        String(port),
        '-U',
        user,
        'grocerycompare_local',
      ]);
    for (const script of ['prisma:generate', 'db:migrate', 'db:seed'])
      run('npm', ['run', script], { cwd: path.join(root, 'backend'), env });
  }
  fs.writeFileSync(
    path.join(root, 'backend/.env.local'),
    `# Generated by npm run db:setup; local development only.\nDATABASE_URL=${databaseUrl}\nALLOW_DEMO_DATA=true\n`,
    { mode: 0o600 },
  );
  console.log(
    'Project database ready. Start the API with npm run backend:dev. Local data is retained when stopped.',
  );
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
